### ISSUE TITLE
Stuck in "Syncing your Mail" forever 

### ISSUE THREAD

**Issue by fakeid30** [Foundry376/Mailspring#158]
##### What operating system are you using?

Arch Linux
...

##### What version of Mailspring are you using?

1.0.4
...

**Bug?**

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
ALL
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
1. Try to sync a reasonably large inbox with 6+ folders. 
2. See the app stuck in syncing your mail 
![screenshot_20171014_131331](https://user-images.githubusercontent.com/26362832/31573649-88f8d118-b0af-11e7-9d56-da60eac8ea0b.png)

--
Note : 

https://github.com/Foundry376/Mailspring/issues/91 This issue seems to be related. But I don't have high memory usage. So I opened new issue.

**Comment by BYTeXperience** [comment]
I'm encounter the same problem on Windows 10 Pro, Mailspring versions 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, and 8 accounts (2 * GMAIL, 2 * YAHOO, 2 * OUTLOOK, 2 * IMAP).

**Comment by giedriusStan** [comment]
Having the same issue on Arch Linux. I have two email accounts set up. One was synced with no issues (outlook) and another (SMTP) always getting "Encountered an error while syncing".

**Comment by orcunbaslak** [comment]
Same as well.

**Comment by rezhajulio** [comment]
I also encountered this issue. Arch linux + Mailspring 1.0.4 with 1 GSuite Account 200k+ emails

**Comment by oserban** [comment]
I occasionally had reset the mail cache and kill the sync client because of this. On the other hand, there is nothing useful related to this on the mailsync logs.

**Comment by IanVaughan** [comment]
I get this as well, and had it with Nylas as well, but with Mailspring I get the added errors as above, the red "Encountered error while syncing".
I've tried re-authing the account, removing and adding, deleting the app and installing again.
It gets so far syncing really well, and then starts throwing up.
This only occurs for 1 of the two gmail accounts I sync, my personal one synced fine and the "Syncing your Mailbox" went away.
But when I added my work account, after a while, it starts giving this error.
Its worse with Mailspring, as with Nylas it was just "always" syncing, but with Mailspring it constanly pops up the red "Encountered error...".
I would really like to help fix this, as Mailspring seem to have fixed some of my little annoyances with Nylas.
I tried debugging, but am a Ruby dev so not great at web, but if I can help at all please get in touch.

**Comment by fakeid30** [comment]
@bengotow are you aware of this issue ?

**Comment by rezhajulio** [comment]
Upgrading to 1.0.5 fix this issue for me

**Comment by JunnanZ** [comment]
I have the same issue. Arch Linux, Mailspring 1.0.5. I have an Office 365 account and the syncing is always stuck at the drafts folder of this account (that is, only the drafts is blinking after expanding the syncing status) and CPU usage is high.

**Comment by oserban** [comment]
I think both of you are right:
- In my case the draft sync problem has been fixed for my IMAP account
- but it still persists for Office 365 accounts

**Comment by fakeid30** [comment]
I still have it on my outlook account on 1.0.5

**Comment by SreckoM** [comment]
Have same problem on one of gmail accounts. It was working OK until 1.0.5. Syncing forever, and sometimes drops Error syncing.

**Comment by bengotow** [comment]
Hey folks - I'm pushing a fix for the "Unable to fetch body for message "Deleting..." (Drafts UID 0). Error ErrorFetch" issue, and that may resolve this in some scenarios.

For other accounts that are syncing forever, could you look in the mailsync logs (in ~/.config/Mailspring/mailsync-***.log on Linux, ~/Library/Application Support/Mailspring on macOS) and see if you're seeing `SyncNow: unable to get folder status ` consistently, every time the app runs through a "sync loop"?

It looks like there's a scenario where if a folder can't be fetched consistently, it'd just stay in "syncing..." state forever. It'd be really useful to know what your IMAP server is responding with (eg: `ErrorConnection` - hopefully something other than that one) so the app can stop trying that folder over and over.

**Comment by fakeid30** [comment]
@bengotow seems like I have this problem
![screenshot_20171019_142049](https://user-images.githubusercontent.com/26362832/31761113-6bf9e2a0-b4a6-11e7-9dae-769aff17ddd6.png)

**Comment by SreckoM** [comment]
I am getting this error in log:

3526 [2017-10-19 15:05:56.252] [foreground] [info] Idling on folder [Gmail]/All Mail
3526 [2017-10-19 15:05:56.762] [background] [critical]
 *** 
 *** A C++ exception occurred during program execution:
 *** too many SQL variables
 ***

3526 [2017-10-19 15:05:56.777] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

**Comment by giedriusStan** [comment]
31482 [2017-10-19 19:55:25.464] [metadataExpiration] [info] Scanning for expired metadata
31482 [2017-10-19 19:55:25.464] [metadataExpiration] [info] -- Will wake for next expiration in 7201sec
31482 [2017-10-19 19:55:38.080] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** std::bad_alloc
 ***

31482 [2017-10-19 19:55:38.162] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

**Comment by IanVaughan** [comment]
Not sure if this will help much, no errors reported, but it just keeps looping the same few emails:

```
46240 [2017-10-20 14:42:47.305] [main] [info] ------------- Starting Sync (ian@amce.com) ---------------
46240 [2017-10-20 14:42:47.308] [background] [info] Fetching XOAuth2 access token for 0027d614
46240 [2017-10-20 14:42:47.308] [metadata] [info] Metadata delta stream starting...
46240 [2017-10-20 14:42:47.905] [background] [info] Marking all folders as `busy`
46240 [2017-10-20 14:42:47.906] [background] [info] Syncing folder list...
46240 [2017-10-20 14:42:49.187] [background] [info] Syncing folder list...
46240 [2017-10-20 14:42:49.452] [background] [info] syncFolderUIDRange - ([Gmail]/All Mail, UIDs: 353976 - 353986, Heavy: true)
46240 [2017-10-20 14:42:53.151] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: highestmodseq changed, requesting changes...
46240 [2017-10-20 14:42:53.323] [background] [info] syncFolderUIDRange - ([Gmail]/All Mail, UIDs: 353565 - 353986, Heavy: false)
46240 [2017-10-20 14:42:56.525] [foreground] [info] 🔸 Updating message 353976=353976 with subject: 
46240 [2017-10-20 14:42:56.535] [foreground] [info] 🔸 Updating message 353977=353977 with subject: 
46240 [2017-10-20 14:42:56.536] [foreground] [info] 🔸 Updating message 353978=353978 with subject: 
46240 [2017-10-20 14:42:56.538] [foreground] [info] 🔸 Updating message 353979=353979 with subject: 
46240 [2017-10-20 14:42:56.539] [foreground] [info] 🔸 Updating message 353980=353980 with subject: 
46240 [2017-10-20 14:42:56.540] [foreground] [info] 🔸 Updating message 353981=353981 with subject: 
46240 [2017-10-20 14:42:56.541] [foreground] [info] 🔸 Updating message 353982=353982 with subject: 
46240 [2017-10-20 14:42:56.542] [foreground] [info] 🔸 Updating message 353983=353983 with subject: 
46240 [2017-10-20 14:42:56.546] [foreground] [info] 🔸 Updating message 353984=353984 with subject: 
46240 [2017-10-20 14:42:56.547] [foreground] [info] 🔸 Updating message 353985=353985 with subject: 
```

https://pastebin.com/pNfLUxud

**Comment by kporangehat** [comment]
* Mac OS 10.13.1 Beta
* Mailspring v1.0.5
* 3 mail accounts (2 GMail, 1 o365)

The o365 account gets stuck syncing Drafts (same as other users above). High CPU usage. The rest of my folders are solid green on this account and my GMail accounts.

Here's a chunk of what's in the relevant log file:

```
986 [2017-10-20 14:43:50.474] [background] [error] Unable to fetch body for message "Deleting..." (Drafts UID 0). Error ErrorFetch
986 [2017-10-20 14:43:50.476] [background] [warning] SyncNow: unable to get folder status for Archive (ErrorParse), skipping...
986 [2017-10-20 14:44:20.476] [background] [warning] SyncNow: unable to get folder status for Trash (ErrorConnection), skipping...
986 [2017-10-20 14:44:50.598] [background] [warning] SyncNow: unable to get folder status for Deleted Messages (ErrorConnection), skipping...
986 [2017-10-20 14:45:20.708] [background] [warning] SyncNow: unable to get folder status for Deleted Items (ErrorConnection), skipping...
986 [2017-10-20 14:45:50.842] [background] [warning] SyncNow: unable to get folder status for Spam (ErrorConnection), skipping...
986 [2017-10-20 14:46:20.986] [background] [warning] SyncNow: unable to get folder status for Junk E-Mail (ErrorConnection), skipping...
986 [2017-10-20 14:46:50.986] [background] [warning] SyncNow: unable to get folder status for Calendar (ErrorConnection), skipping...
986 [2017-10-20 14:47:21.135] [background] [warning] SyncNow: unable to get folder status for Contacts (ErrorConnection), skipping...
986 [2017-10-20 14:47:51.134] [background] [warning] SyncNow: unable to get folder status for Conversation History (ErrorConnection), skipping...
986 [2017-10-20 14:48:21.282] [background] [warning] SyncNow: unable to get folder status for Builds (ErrorConnection), skipping...
986 [2017-10-20 14:48:51.419] [background] [warning] SyncNow: unable to get folder status for Archive1 (ErrorConnection), skipping...
986 [2017-10-20 14:49:21.419] [background] [warning] SyncNow: unable to get folder status for [Airmail]/Snooze (ErrorConnection), skipping...
986 [2017-10-20 14:49:51.418] [background] [warning] SyncNow: unable to get folder status for [Mailspring] (ErrorConnection), skipping...
986 [2017-10-20 14:50:21.417] [background] [warning] SyncNow: unable to get folder status for Journal (ErrorConnection), skipping...
986 [2017-10-20 14:50:51.529] [background] [warning] SyncNow: unable to get folder status for [Airmail]/To Do (ErrorConnection), skipping...
986 [2017-10-20 14:51:21.576] [background] [warning] SyncNow: unable to get folder status for Later (ErrorConnection), skipping...
986 [2017-10-20 14:51:51.576] [background] [warning] SyncNow: unable to get folder status for N1-Snoozed (ErrorConnection), skipping...
986 [2017-10-20 14:52:21.724] [background] [warning] SyncNow: unable to get folder status for Notes (ErrorConnection), skipping...
986 [2017-10-20 14:52:51.871] [background] [warning] SyncNow: unable to get folder status for Outbox (ErrorConnection), skipping...
986 [2017-10-20 14:53:21.987] [background] [warning] SyncNow: unable to get folder status for Read Later (ErrorConnection), skipping...
986 [2017-10-20 14:53:52.022] [background] [warning] SyncNow: unable to get folder status for [Airmail]/Send Later (ErrorConnection), skipping...
986 [2017-10-20 14:54:22.021] [background] [warning] SyncNow: unable to get folder status for [Airmail]/Memo (ErrorConnection), skipping...
986 [2017-10-20 14:54:52.169] [background] [warning] SyncNow: unable to get folder status for [Airmail]/Done (ErrorConnection), skipping...
986 [2017-10-20 14:55:22.168] [background] [warning] SyncNow: unable to get folder status for SG-Jira (ErrorConnection), skipping...
986 [2017-10-20 14:55:52.168] [background] [warning] SyncNow: unable to get folder status for [Mailspring]/Snoozed (ErrorConnection), skipping...
986 [2017-10-20 14:56:22.167] [background] [warning] SyncNow: unable to get folder status for Starred (ErrorConnection), skipping...
986 [2017-10-20 14:56:52.314] [background] [warning] SyncNow: unable to get folder status for Tasks (ErrorConnection), skipping...
986 [2017-10-20 14:57:17.910] [metadata] [info] Metadata delta stream closed.
986 [2017-10-20 14:57:17.911] [metadata] [info] Metadata delta stream starting...
986 [2017-10-20 14:57:22.317] [background] [warning] SyncNow: unable to get folder status for todo (ErrorConnection), skipping...
986 [2017-10-20 14:57:52.462] [background] [warning] SyncNow: unable to get folder status for [Airmail] (ErrorConnection), skipping...
986 [2017-10-20 14:57:52.462] [background] [info] Sync loop deleting unlinked messages with phase 2.
986 [2017-10-20 14:57:53.259] [background] [info] Sync loop complete.
986 [2017-10-20 14:57:53.259] [background] [info] Syncing folder list...
986 [2017-10-20 14:57:57.158] [background] [info] syncFolderUIDRange - (INBOX, UIDs: 1 - 0, Heavy: false)
986 [2017-10-20 14:57:59.138] [background] [info] syncFolderUIDRange - (Sent Messages, UIDs: 1 - 0, Heavy: false)
986 [2017-10-20 14:58:01.145] [background] [info] syncFolderUIDRange - (Sent Items, UIDs: 1 - 0, Heavy: false)
986 [2017-10-20 14:58:02.388] [background] [error] syncFolderUIDRange - Fetching full headers for 257
986 [2017-10-20 14:58:03.737] [background] [info] 🔸 Updating message 4353=4350 with subject: Re: multi-location question
986 [2017-10-20 14:58:03.758] [background] [info] 🔸 Updating message 4347=4342 with subject: multi-location question
986 [2017-10-20 14:58:03.778] [background] [info] 🔸 Updating message 4313=4311 with subject: Re: Fwd: [shotgun-dev] Hiring at Shotgun
986 [2017-10-20 14:58:03.800] [background] [info] 🔸 Updating message 4308=4306 with subject: inquiring...
986 [2017-10-20 14:58:03.823] [background] [info] 🔸 Updating message 4304=4301 with subject: Re: Fwd: [shotgun-dev] Hiring at Shotgun
986 [2017-10-20 14:58:03.847] [background] [info] 🔸 Updating message 4298=4296 with subject: Re: Audio tracking in SG?
```

**Comment by fakeid30** [comment]
Still have the problem with 1.0.6 

@bengotow are you aware ?

**Comment by davduf** [comment]
Syncing my mailbox with 1.0.6  is endless forever too :-)

FEDORA 26
GNOME Shell 3.24.3

Thank you so much!
All my best

David

**Comment by davduf** [comment]
Same here with 1.0.6

Fedora 26
GNOME Shell 3.24.3

**Comment by oserban** [comment]
In my case, it was not solved at first, but I reset my local cache and since then I had a few successful synchronisations after restarts or shutdowns .

**Comment by ET-Bent** [comment]
Same here, Fedora 26, GNOME Shell 3.24.3 , Mailspring `1.0.6-9448c884`, two IMAP accounts.

Both accounts sync successfully after resetting the mailcache. After a restart of Mailspring the sync gets stuck and hangs on `Indexing messages` which uses one CPU core 100% and uses all RAM available (12GB) rendering the laptop useless.

**Comment by IanVaughan** [comment]
v1.0.6 has seemed to have solved it!!!

It took a while, and I saw the error I had previously a few times: "Encountered error while syncing".

But after a few close/reopens, and time past, the "Syncing your Mailbox" has gone!

Amazing work, and amazing fixes done to this amazing email client!

**Comment by fakeid30** [comment]
I still have this on 1.0.7

**Comment by giedriusStan** [comment]
me too, I remember Nylas Mail was indexing my email for at least 8 hours, but it finished eventually. Mailspring however promps an error after a minute or two of indexing

**Comment by giedriusStan** [comment]
I just updated to 1.0.7 and cleared cache, I seem to no longer receive this error!

**Comment by davduf** [comment]
I just updated to 1.0.7 and cleared cache, I seem to no longer receive 
this error too

BUT

It won't sync anymore...

I have to clear cache everytime :-(


Le 30/10/2017 à 09:27, Giedrius Stan a écrit :
>
> I just updated to 1.0.7 and cleared cache, I seem to no longer receive 
> this error!
>

**Comment by TheWidowLicker** [comment]
I have this syncing issue using manjaro (Arch), mailspring 1.0.7 and Yahoo email account.
I have cleared the cache and the entire .config/mailspring folder repeatedly but once i setup it sits constatntly syncing on all folders.
The log tells nothing of importance, it just repeatedly says the same messsages over and over.
3019 [2017-11-01 07:49:27.376] [background] [info] Syncing folder list...
3019 [2017-11-01 07:49:29.237] [background] [info] Syncing folder list...
3019 [2017-11-01 07:49:29.530] [background] [info] syncFolderUIDRange - (INBOX, UIDs: 1 - 347928, Heavy: true)
3019 [2017-11-01 07:49:30.583] [foreground] [info] syncFolderUIDRange - (INBOX, UIDs: 348508 - 348678, Heavy: false)
3019 [2017-11-01 07:49:41.682] [foreground] [info] Connection does not support idling. Locking until more to do...
3019 [2017-11-01 07:49:42.363] [metadataExpiration] [info] Scanning for expired metadata
3019 [2017-11-01 07:49:42.363] [metadataExpiration] [info] -- Will wake for next expiration in 7201sec
3019 [2017-11-01 07:51:39.560] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorFetch","retryable":true,"what":"std::exception"}

This is a terrible pity as I think this could be a great mail reader but is somewhat useless as of now.
Does anyone have any suggestions on other mail readers (not eveolution or thunderbird) as I cannot be days without my email and still ahve to add in 2 more accounts.
Regards

**Comment by oserban** [comment]
To be completely honest, I found Mailspring to be the best option for me, especially if you don't like the other such as Thunderbird, Evolution or Geary. 
There are still some bugs with mailsync, but I worked with email servers before and I know that everyone interprets the IMAP protocol in a different way. It's definitely not fun to debug all these issues.

**Comment by TheWidowLicker** [comment]
Mailspring seems great but if I cant get my mail then it is of no use as a mail reader.

**Comment by bengotow** [comment]
Hey folks—this issue should be largely resolved in 1.0.9 which will ship tomorrow. Basically, Mailspring would get stuck "syncing your mail" indefinitely if one or more of the recent messages in your account were permanently "corrupt" or otherwise un-retrievable. (Mailspring pre-fetches the contents of the last three months of your email to build an offline search index.) It turns out, this happens occasionally, even for large providers like Gmail. 

Starting in 1.0.9, Mailspring will make one attempt to fetch the body of a message for indexing, and if it fails, it will wait until you click that message to try to fetch it again. This means that any rouge messages your mailserver cannot provide or badly corrupted messages that crash the sync worker won't stop the app from completing its pass through your mailbox.

There are a handful of other ways "syncing your mail" can get stuck forever but I expect this is the biggest one by a good margin. Stay tuned—

**Comment by MirkoLedda** [comment]
I have the same problem on macOS. It get stuck on "syncing your email" with ~20% CPU usage (which is a lot). Reloading the app via the developer tab seems to solve this. The log seems to indicate that the syncing loop completed but I still see "syncing your email" on the bottom left of the app.

19611 [2017-12-13 10:37:58.329] [background] [info] Syncing folder list...
19611 [2017-12-13 10:37:58.773] [background] [info] syncFolderUIDRange - ([Gmail]/All Mail, UIDs: 52212 - 52651, Heavy: false)
19611 [2017-12-13 10:37:59.607] [background] [info] syncFolderUIDRange - ([Gmail]/Trash, UIDs: 1 - 31409, Heavy: false)
19611 [2017-12-13 10:38:00.253] [background] [info] syncFolderUIDRange - ([Gmail]/Spam, UIDs: 1 - 26308, Heavy: false)
19611 [2017-12-13 10:38:00.677] [background] [info] Sync loop deleting unlinked messages with phase 2.
19611 [2017-12-13 10:38:00.678] [background] [info] Sync loop complete.

**Comment by alexandru-calinoiu** [comment]
Restarting in dev mode will start over and do a fresh sync.

**Comment by btstream** [comment]
It looks like that sync still get some problems， I still get lots of log info like 

```
41154 [2018-01-31 14:18:12.442] [background] [warning] Unable to insert file ID JayuPUt2ij3BrM93gJb3rfU1t6m5TDHNSaD57theE - it must already exist.
41154 [2018-01-31 14:18:22.674] [background] [warning] Unable to insert file ID ZduFQK3sWGatphzELsJodaGYK42UkWJhhPPhJRp4M - it must already exist.
41154 [2018-01-31 14:18:22.732] [background] [warning] Unable to insert file ID 6EMKYfCbqwZpCCyqGQBFJowxd5G34iAvmUXEVCHZE - it must already exist.
41154 [2018-01-31 14:18:25.639] [background] [warning] Unable to insert file ID P8aV1DCwEQxbdNzqNtz7CCwDRAiL58zVEi3J15uuE - it must already exist.
41154 [2018-01-31 14:18:28.019] [background] [warning] Unable to insert file ID LyNVewmdLn2DmCVzvfEWZRPotD54RZCTtfSSAnaDw - it must already exist.
41154 [2018-01-31 14:18:28.153] [background] [warning] Unable to insert file ID pcd5vqHctbCNmj467As2HsC5j3rUTAw6mgoYasjKK - it must already exist.
41154 [2018-01-31 14:18:29.143] [background] [warning] Unable to insert file ID RAp2GpDKGTTR9bygrSyLAszys9QajGb8ZZdL2FkVY - it must already exist.
41154 [2018-01-31 14:18:29.283] [background] [warning] Unable to insert file ID JdMYoDdPUa2FhhUa1Jihbq7fLgWoZkh4hJXn78W7D - it must already exist.
41154 [2018-01-31 14:18:34.148] [background] [warning] Unable to insert file ID A1HnNtKiycZHb3uptZDCg4UNR22Nn7BWoioDxEgfq - it must already exist.
41154 [2018-01-31 14:18:37.492] [background] [warning] Unable to insert file ID N4ZcjxZRRMtnxAJcfJJtXRSoi3Tm3Wba73wvcMAFy - it must already exist.
41154 [2018-01-31 14:18:37.540] [background] [warning] Unable to insert file ID bas1a7mBcP4nj75iWzzkHp9euEaMHpqFTCJzQP5bJ - it must already exist.
41154 [2018-01-31 14:18:37.858] [background] [warning] Unable to insert file ID AuCxCZRRi8bMZadjNTomakxHkGBUYFpSsnn7WyUMW - it must already exist.
41154 [2018-01-31 14:18:38.170] [background] [warning] Unable to insert file ID MVRwdhBBRpjxvTtKhVMFHUn7MKce8hnLxDtsDTx37 - it must already exist.
```

And some actions such as `mark as read` or `delete` need a lot of sync jobs to  take effect on upstream server. 

P.S my mail service is a coremail based service.

**Comment by jimtyranski** [comment]
Cannot sync my gsuite account.  Here is my mailsync log:
1003 [2018-05-22 11:10:56.561] [main] [info] Identity created at 1527026097 - using ID Schema 1
1003 [2018-05-22 11:10:56.563] [main] [info] ------------- Starting Sync (first.last@companydomain.com) ---------------
1003 [2018-05-22 11:10:56.564] [main] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** no such table: Task
 ***

1003 [2018-05-22 11:10:56.564] [metadata] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** no such table: _State
 ***

1003 [2018-05-22 11:10:56.564] [background] [info] Fetching XOAuth2 access token from Gmail for fcdf4968
1003 [2018-05-22 11:10:56.571] [main] [critical]  *** Stack trace:
 ***   SQLite::Statement::Ptr::Ptr(sqlite3*, string&)
 ***   SQLite::Statement::Statement(SQLite::Database&, string const&)
 ***   vector MailStore::findAll(Query&)
 ***   TaskProcessor::cleanupTasksAfterLaunch()
 ***   runListenOnMainThread(shared_ptr)
 ***   main
 ***

**Comment by westr029** [comment]
I tried caching a few times. It kept saying 'Scanning messages'. However, every time it got stuck on different folders.

I have Mailspring 1.4.2 installed via snap on Ubuntu 16.04

Below a selection of the log-file after some time of scanning messages, when warnings appear:
```
18936 [2018-08-21 13:22:20.921] [background] [warning] SyncNow: unable to get folder status for Calendar (ErrorConnection), skipping...
18936 [2018-08-21 13:22:50.929] [background] [warning] SyncNow: unable to get folder status for Sync Issues/Server Failures (ErrorConnection), skipping...
18936 [2018-08-21 13:22:56.637] [background] [warning] SyncNow: unable to get folder status for Sync Issues/Local Failures (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:56.645] [background] [warning] SyncNow: unable to get folder status for Sync Issues/Conflicts (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:56.652] [background] [warning] SyncNow: unable to get folder status for Sync Issues (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:56.662] [background] [warning] SyncNow: unable to get folder status for RSS Feeds (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:56.825] [background] [warning] SyncNow: unable to get folder status for Outbox (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:56.832] [background] [warning] SyncNow: unable to get folder status for Ongewenste e-mail (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:56.837] [background] [warning] SyncNow: unable to get folder status for Notes (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:57.012] [background] [warning] SyncNow: unable to get folder status for Mailspring/Snoozed (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:57.019] [background] [warning] SyncNow: unable to get folder status for Mailspring (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:57.025] [background] [warning] SyncNow: unable to get folder status for Journal (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:57.184] [background] [warning] SyncNow: unable to get folder status for Folders/Speed Reading (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:57.191] [background] [warning] SyncNow: unable to get folder status for Folders/Publications (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:57.372] [background] [warning] SyncNow: unable to get folder status for Folders/PhD project (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:57.543] [background] [warning] SyncNow: unable to get folder status for Folders/Paper Alerts (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:57.553] [background] [warning] SyncNow: unable to get folder status for Folders/Loon ed (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:59.091] [background] [warning] SyncNow: unable to get folder status for Folders/Links (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:59.100] [background] [warning] SyncNow: unable to get folder status for Folders/GroIMP (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:59.263] [background] [warning] SyncNow: unable to get folder status for Folders (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:59.450] [background] [warning] SyncNow: unable to get folder status for Conversation History (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:59.457] [background] [warning] SyncNow: unable to get folder status for Contacts/Skype for Business Contacts (ErrorNonExistantFolder), skipping...
18936 [2018-08-21 13:22:59.465] [background] [warning] SyncNow: unable to get folder status for Contacts (ErrorNonExistantFolder), skipping...
```

As far as I could find there are 2 errors:
* `ErrorNonExistantFolder` - these folders are present in my exchange account
* `ErrorConnection` - this error seems to mostly occur at folders for which MailSpring is not designed, like Calendar and Contacts.

@bengotow, please let me know if I need to try out anything else or if you need more information.

**Comment by patatus** [comment]
Hello!
I'm having the same issue with an O365 account (no problem with gmail).
It's been "scanning messages" for several days now, both on macOS 10.13 and windows 10.

I have this log on macOS:

```
3522 [2018-09-17 16:37:16.930] [main] [info] ------------- Starting Sync (office 365 account) ---------------
3522 [2018-09-17 16:37:16.960] [metadata] [info] Metadata delta stream starting...
3522 [2018-09-17 16:37:16.962] [background] [info] Marking all folders as `busy`
3522 [2018-09-17 16:37:16.969] [background] [info] Syncing folder list...
3522 [2018-09-17 16:37:19.010] [background] [info] Syncing folder list...
3522 [2018-09-17 16:37:19.346] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 60194, Heavy: false
3522 [2018-09-17 16:37:19.987] [background] [info] - remote=3434, local=0
3522 [2018-09-17 16:37:19.995] [background] [info] - Fetching full headers for 3434 (of 3434 needed)
3522 [2018-09-17 16:37:20.350] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}
3522 [2018-09-17 16:37:20.941] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 60695 - 61009, Heavy: false
3522 [2018-09-17 16:37:21.462] [foreground] [info] - remote=101, local=101
3522 [2018-09-17 16:37:21.483] [foreground] [info] Idling on folder INBOX
3522 [2018-09-17 16:37:31.933] [metadataExpiration] [info] Scanning for expired metadata
3522 [2018-09-17 16:37:31.933] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
3522 [2018-09-17 16:39:20.350] [background] [info] Syncing folder list...
3522 [2018-09-17 16:39:20.586] [background] [info] Sleeping after exception: {"debuginfo":"syncFoldersAndLabels - fetchAllFolders","key":"ErrorConnection","retryable":true,"what":"std::exception"}
3522 [2018-09-17 16:41:20.585] [background] [info] Syncing folder list...
3522 [2018-09-17 16:41:22.694] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 60194, Heavy: false
3522 [2018-09-17 16:41:23.344] [background] [info] - remote=3434, local=0
3522 [2018-09-17 16:41:23.352] [background] [info] - Fetching full headers for 3434 (of 3434 needed)
3522 [2018-09-17 16:41:23.691] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}
```

Thanks a lot!

**Comment by sajran** [comment]
I have the same problem. This is the log that keeps repeating every 2 minutes:
```
32384 [2019-03-18 21:51:38.904] [background] [info] Syncing folder list...
32384 [2019-03-18 21:51:38.934] [background] [info] syncFolderChangesViaCondstore - INBOX: modseq 390599644157044 to 390599644157044, uidnext 562 to 562
32384 [2019-03-18 21:51:38.956] [background] [info] syncFolderChangesViaCondstore - Sent: modseq 390599322937857 to 390599322937857, uidnext 46 to 46
32384 [2019-03-18 21:51:38.969] [background] [info] syncFolderChangesViaCondstore - Drafts: modseq 390590531405197 to 390590531405197, uidnext 95 to 95
32384 [2019-03-18 21:51:39.002] [background] [info] syncFolderChangesViaCondstore - Trash: modseq 390599628332383 to 390599628332383, uidnext 313 to 313
32384 [2019-03-18 21:51:39.014] [background] [info] syncFolderChangesViaCondstore - Spam: modseq 313240727430115 to 313240727430115, uidnext 1 to 1
32384 [2019-03-18 21:51:39.022] [background] [info] syncFolderChangesViaCondstore - Archiwum: modseq 390599641730941 to 390599641730941, uidnext 253 to 253
32384 [2019-03-18 21:51:39.053] [background] [info] syncFolderChangesViaCondstore - Mailspring/Snoozed: modseq 390598115813722 to 390598115813722, uidnext 1 to 1
32384 [2019-03-18 21:51:39.073] [background] [info] syncFolderChangesViaCondstore - Trash/Wys&AUI-ane: modseq 390599310865517 to 390599310865517, uidnext 7 to 7
32384 [2019-03-18 21:51:39.090] [background] [info] syncFolderChangesViaCondstore - Shared Folders/User/Postmaster/Komunikaty: modseq 390599506695236 to 390599506695236, uidnext 291 to 291
32384 [2019-03-18 21:51:39.106] [background] [warning] SyncNow: unable to get folder status for Shared Folders/User/Postmaster/NowySpam (ErrorNonExistantFolder), skipping...
32384 [2019-03-18 21:51:39.106] [background] [info] Sync loop deleting unlinked messages with phase 2.
32384 [2019-03-18 21:51:39.107] [background] [info] Sync loop complete.
```
It's pretty weird because judging by the log it doesn't try to sync the non-existent folder continuously. However in the GUI it says that this exact folder is being synced and CPU usage is very high: 20 - 30% which makes the program unusable.

**Comment by Vehmloewff** [comment]
This same thing happens to me too.

Ubuntu `18.04.3`
Mailspring version `1.6.3-134a0e55`

![Screenshot from 2019-08-21 06-59-45](https://user-images.githubusercontent.com/45398751/63430069-4ee1f580-c3e1-11e9-9f7d-a2e7ce8a13c4.png)

It appears, however, that all new emails are being received, and all sent emails are arriving at the correct users inbox.

**Comment by dcarlson-rvbd** [comment]
I am on Mint 19.2, and I installed Mailspring 1.7.2 two days ago and updated to 1.7.3 today. I have four O365 accounts. Three sync perfectly fine, the other does not. The one that does not does receive new mail, but it eats up CPU trying to get the other folders synced up. I've checked that I have no folders with dots in the name, and I've also gone into OWA and emptied deleted items, etc. I have tried to rebuild cache several times and I've deleted and re-added as an IMAP account all to no avail.

Here is a current log snippet:
`---------------
2704 [2019-12-06 16:25:33.148] [metadata] [info] Metadata delta stream starting...
2704 [2019-12-06 16:25:33.159] [background] [info] Marking all folders as `busy`
2704 [2019-12-06 16:25:33.171] [background] [info] Syncing folder list...
2704 [2019-12-06 16:25:34.231] [background] [info] Syncing folder list...
2704 [2019-12-06 16:25:34.310] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 55537, Heavy: false
2704 [2019-12-06 16:25:34.558] [background] [info] - remote=2143, local=0
2704 [2019-12-06 16:25:34.579] [background] [info] - Fetching full headers for 2143 (of 2143 needed)
2704 [2019-12-06 16:25:34.616] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}
2704 [2019-12-06 16:25:34.898] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 55641 - 56288, Heavy: false
2704 [2019-12-06 16:25:35.035] [foreground] [info] - remote=101, local=101
2704 [2019-12-06 16:25:35.037] [foreground] [info] Idling on folder INBOX
2704 [2019-12-06 16:25:48.153] [metadataExpiration] [info] Scanning for expired metadata
2704 [2019-12-06 16:25:48.153] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec`

![Screenshot from 2019-12-06 16-35-33](https://user-images.githubusercontent.com/49345903/70358597-bcf2e100-1847-11ea-9dad-496514156a79.png)

**Comment by swastikmishra** [comment]
I ran into the same issue. After checking the logs, I found that Gmail OAuth Tokens were revoked for some security reasons. So MailSpring didn't throw any error or didn't ask to reauthenticate.

```
onse Code: 400","retryable":true,"what":"std::exception"}
4538 [2020-01-06 09:46:51.287] [background] [info] Fetching XOAuth2 access token from Gmail for e70ab24c
4538 [2020-01-06 09:46:53.187] [background] [info] Sleeping after exception: {"debuginfo":"https://www.googleapis.com/oauth2/v4/token RETURNED {\n  \"error\": \"invalid_grant\",\n  \"error_description\": \"Token has been expired or revoked.\"\n}","key":"Invalid Response Code: 400","retryable":true,"what":"std::exception"}
```

Reauthenticating the accounts worked for me.

**Comment by mwspicer** [comment]
I had the same problem of tokens being revoked. I had to re-authenticate and then rebuild the cache to get it working.

**Comment by ForNeVeR** [comment]
Just hit the same issue. It would be good if Mailspring would notify the user about that `invalid_grant` error code.

**Comment by RaitoBezarius** [comment]
I'm hitting this issue with an insanely long inbox name: `DUPLICATA-60-JOURS-60-DAYS`, I don't know if there's something specific to it or not

**Comment by sgtcoder** [comment]
I am also getting syncing your mailbox indefinitely. And this ticket has been open for about 4 years now. When will we see a fix?

**Comment by ForNeVeR** [comment]
Honestly, the issue never reappeared for me since February. Looks like the main problem (processing OAuth errors from GMail and other providers) has been fixed since then.

So, probably, you better check the logs, and maybe raise a new, more focused issue about the actual underlying problem?

**Comment by CodeMouse92** [comment]
It's difficult to know whether this issue is still active because of the same causes, or new ones. If you're experiencing this, please open a bug report on our new Discourse community (https://community.getmailspring.com) or upvote an existing bug report there.

We're closing and locking the issue here as part of this migration.

We hope to see you on Discourse soon!

-The Mailspring Team
