### ISSUE TITLE
Error syncing after update to 1.7.1

### ISSUE THREAD

**Issue by scottmacquoid** [Foundry376/Mailspring#1682]
There is an issue in syncing with mail after the update to 1.7.1
on both Windows and Ubuntu systems.

Sending emails don't work most of the time and when it is sent, no tracking working (paid account)

I downgraded to 1.6.3 and everything worked fine, but the problem is with auto update once restarted, so please either fix this issue, or tell me how to stop the auto update

**Comment by bengotow** [comment]
Hey! Sorry for the hassle @scottmacquoid — this should be fixed by 1.7.2 tomorrow!

**Comment by scottmacquoid** [comment]
@bengotow Thanks, mate.. I know I can count on mailspring

**Comment by markkiambo** [comment]
Hey.. 

I also experienced the same sync issue after upgrading to 1.7.1 on Mac OS. I downgraded to 1.7.0 to restore the sync functionality.

**Comment by scottmacquoid** [comment]
Just updated to version 1.7.2.. still the same issue, now it doesn't send at all.. please revert to version 1.6.3 and remove the auto update in windows, I can't use the email at all now

**Comment by njascanu** [comment]
Upgraded from 1.7.1 to 1.7.2 and the syncing error is still present:
6457 [2019-10-22 21:12:31.844] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
6457 [2019-10-22 21:12:37.847] [calContacts] [critical] 
 ***
 *** An exception occurred during program execution: 
 *** (unknown exception details)
 ***

6457 [2019-10-22 21:12:37.852] [calContacts] [critical]  *** Stack trace:
 ***   clone
 ***

**Comment by nielsdk2677** [comment]
I'm having the same issue. 
![test](https://user-images.githubusercontent.com/56926548/67402856-73a94380-f5b1-11e9-87b2-38a68e147cc0.png)
Since 1.7.1 on Mac this is an error every 2 minutes orso... (screenshot)
Issue persists with 1.7.2 update.

Triple checked all mail settings, they are 100% correct.
Checked with my webhost, they have no known errors.

I'm running Mac OS 10.11.6 (latest version I can use since i'm on a 2009 Mac Pro)
Error message attached.

I have tried rebuilding cache, uninstalled Mailspring completely, then reinstalled it, updated connection settings, deleted accounts then added them again... issue remains...

**Comment by scottmacquoid** [comment]
I was able to get around this issue for now until you release a better version by installing version 1.6.3 and then deleting the update file from C:\Users\username\AppData\Local\Mailspring to prevent it from updating till I get a confirmation that this issue has been resolved @bengotow hopefully you can fix this issue soon

**Comment by joshnewans** [comment]
Version 1.7.2 also did not resolve this issue for me on Linux.


```
14610 [2019-10-25 14:14:34.916] [main] [info] Identity created at 1554039823 - using ID Schema 1
14610 [2019-10-25 14:14:34.917] [main] [info] ------------- Starting Sync (xxxxx@xxxxx.xxxx) ---------------
14610 [2019-10-25 14:14:34.920] [metadata] [info] Metadata delta stream starting...
14610 [2019-10-25 14:14:37.920] [background] [info] Marking all folders as `busy`
14610 [2019-10-25 14:14:37.936] [background] [info] Syncing folder list...
14610 [2019-10-25 14:14:38.090] [background] [info] Syncing folder list...
14610 [2019-10-25 14:14:38.166] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 12905, Heavy: true
14610 [2019-10-25 14:14:38.441] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 13551 - 13667, Heavy: false
14610 [2019-10-25 14:14:38.520] [foreground] [info] - remote=101, local=101
14610 [2019-10-25 14:14:38.532] [foreground] [info] Idling on folder INBOX
14610 [2019-10-25 14:14:49.921] [metadataExpiration] [info] Scanning for expired metadata
14610 [2019-10-25 14:14:49.921] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
14610 [2019-10-25 14:14:54.876] [] [critical] 
 ***
 *** An exception occurred during program execution: 
 *** (unknown exception details)
 ***

14610 [2019-10-25 14:14:54.893] [] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***
```

**Comment by serge-kaimin** [comment]
the same issue there on Ubuntu 19.04 and Ubuntu 19.10 when sync imap account.

23675 [2019-10-29 13:36:33.320] [calContacts] [critical] 
 ***
 *** An exception occurred during program execution: 
 *** (unknown exception details)
 ***

23675 [2019-10-29 13:36:33.346] [calContacts] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

**Comment by nielsdk2677** [comment]
Bedankt voor je bericht!
Op 28 en 29 oktober ben ik met volle focus aan de slag op Podlab XL, een hoog kwalitatief opleidingstraject voor geëngageerde podcastmakers. Meer info op podlab.be
Ik ben deze dagen iets moeilijker te bereiken. Op 30/10 mag je zeker een antwoord verwachten.
Heb je onze podcast Creative Minds al ontdekt? Luister hier! 

Tot snel.
Groeten

Niels De KeukelaereWajoo Podcasts | Founder, Creator of thingswww.wajoo.be

**Comment by scottmacquoid** [comment]
Any updates? @bengotow

**Comment by JonGarbayo** [comment]
A fix is really needed @bengotow :/ Any news?

**Comment by joshnewans** [comment]
Also is this a duplicate?
#1693

**Comment by JonGarbayo** [comment]
Yes, it seems like the same problem.

**Comment by nielsdk2677** [comment]
It's been one month and still no fix or update. Sad to say but i'm switching mail client for good. Unfortunately Mailspring has proven to be unreliable. Too bad cause I loved it.

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/crash-on-sync-no-stack-trace/419

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
