### ISSUE TITLE
Bug: Still completely unusable even in the newest version. Office365, Outlook, IMAP, Gmail. Nothing works!

### ISSUE THREAD

**Issue by pythonInRelay** [Foundry376/Mailspring#1924]
Office365, Outlook, IMAP and even Gmail accounts. **Nothing is working.**

![one](https://i.ibb.co/TrYbyC0/Screenshot-2.png)
![two](https://i.ibb.co/bLmHFjr/Screenshot-3.png)
![three](https://i.ibb.co/NmMqzNz/Screenshot-4.png)
![four](https://i.ibb.co/J55ZW6w/Screenshot-5.png)

It seems the only thing you fixed was getting rid of the blank white screen that wouldn't go away in the last version when trying to add an account.

Seriously guys I hate to be that guy but for $8 a month, it took you months to release a new version and it still doesn't even work. Please test your releases before sending them to production.

**Comment by kurisu-gh** [comment]
I occasionally visit this repo to see if MailSpring has finally solved these issues. The answer seems to be a resounding 'no'. Related to your problem is issue https://github.com/Foundry376/Mailspring/issues/304 which has been reported almost 3 years ago and no progress. Unfortunately, this beautiful app with promising features is not worth $8/month, perhaps not even for free considering the headaches and negative impact it had on my productivity in the past. I've long since moved on.

**Comment by bengotow** [comment]
Hey folks! I'm afraid this ticket isn't terribly useful because it doesn't include the platform you're running on or the other info requested in the issue template — it looks like Mailspring is unable to sync any mail provider, which means it's probably an issue with password storage (on Linux you may need libsecret, any chance you clicked through a warning when you first launched the app?) I would also suggest you go to Preferences > General and click "Reset Cache". If that works, it'd be super useful. This could also happen if your disk is full, though there's usually error messaging around that as well.

If you go to Developer > Show Mailsync Logs and look at the bottom of one of the `mailsync-***.log` files in the folder that is revealed, there's most likely a more specific error message there that would be helpful to see too!

**Comment by kurisu-gh** [comment]
@bengotow I highly suggest you once again take a look at other very related and unresolved issues such as https://github.com/Foundry376/Mailspring/issues/304 which:
- Have the issue info you requested
- Have users posting their Mailsync logs
- Have users trying reset/clear cache with only temporary (minutes to hours) or no improvement
- Have users reporting that they're not using virtual folders

Getting MailSpring to work well with popular mail providers has always been issue that has never been properly addressed. Many users in https://github.com/Foundry376/Mailspring/issues/304 have provided a lot info, only to be left in the dark.

**Comment by bengotow** [comment]
Ahh I'll take a look at that one! I think I commented there that Mailspring doesn't support virtual folders, but it looks like folks are still trying to make it work with accounts that use virtual folders and being upset that it doesn't - probably need to block Zimbra, etc. right at the IMAP connection screen, but maybe one day I can overhaul sync to fix that one.

In the meantime I've also pushed up 78a0748f7728433501ea5280819fa79a8127cb62 which adds a one-click button to fetch the error info I need to debug issues like this one above, so hopefully these github issues are more actionable more often!

**Comment by pythonInRelay** [comment]
@bengotow

I'm using Windows 10.

I've cleared the cache and restarted my machine and the app. It gives a ![big white box again](https://i.ibb.co/X2PQ5PG/Screenshot-1.png) just like the bug in 1.7.4 when clicking "Try Reconnecting" under the errored account.

I don't have full disk space. No VPN or weird proxy or DNS settings or anything like that.

There is most certainly a severe problem with your service that you are experiencing and I mean this in the nicest way, it may be time to outsource this to a consultant or otherwise to have these problems fixed once and for all.

**Comment by CarlosRebolledo** [comment]
Dear, in Windows 10, I have been able to add Outlook.com accounts without problem (v 1.7.5.)

**Comment by kurisu-gh** [comment]
> but it looks like folks are still trying to make it work with accounts that use virtual folders and being upset that it doesn't - probably need to block Zimbra, etc. right at the IMAP connection screen, but maybe one day I can overhaul sync to fix that one.

As I've mentioned in my reply, there are several users there who confirmed that they are **NOT** using virtual folders and are still dealing with the same sync issue.

**Comment by pythonInRelay** [comment]
@bengotow Well mate 1.7.6 seems to have fixed *some things*. I can now re-authenticate with Office365 and IMAP however Gmail is still not working. I'm using an email that uses gmail but does not have the @gmail.com domain.

Here's my log, with my email removed for privacy reasons:

`Mailspring Version: 1.7.6-e94bb759
Platform: win32
Account State: sync_error
Account Provider: gmail
IMAP Server: imap.gmail.com
SMTP Server: smtp.gmail.com
--------------------------------------------
6268 [2020-04-23 20:20:26.615] [metadata] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   _is_exception_typeof
 ***   _is_exception_typeof
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***

7420 [2020-04-23 20:20:42.706] [main] [info] Identity created at 1576437679 - using ID Schema 1
7420 [2020-04-23 20:20:42.707] [main] [info] ------------- Starting Sync (******@*****.****.***) ---------------
7420 [2020-04-23 20:20:43.544] [metadata] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   _is_exception_typeof
 ***   _is_exception_typeof
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***

20380 [2020-04-23 20:20:43.608] [main] [info] Identity created at 1576437679 - using ID Schema 1
20380 [2020-04-23 20:20:43.610] [main] [info] ------------- Starting Sync (******@*****.****.***) ---------------
20380 [2020-04-23 20:20:44.328] [metadata] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   _is_exception_typeof
 ***   _is_exception_typeof
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***

15800 [2020-04-23 20:20:44.393] [main] [info] Identity created at 1576437679 - using ID Schema 1
15800 [2020-04-23 20:20:44.394] [main] [info] ------------- Starting Sync (******@*****.****.***) ---------------
15800 [2020-04-23 20:20:45.113] [metadata] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   _is_exception_typeof
 ***   _is_exception_typeof
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***

20064 [2020-04-23 20:20:45.173] [main] [info] Identity created at 1576437679 - using ID Schema 1
20064 [2020-04-23 20:20:45.175] [main] [info] ------------- Starting Sync (******@*****.****.***) ---------------
20064 [2020-04-23 20:20:45.894] [metadata] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   _is_exception_typeof
 ***   _is_exception_typeof
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***

18396 [2020-04-23 20:20:45.955] [main] [info] Identity created at 1576437679 - using ID Schema 1
18396 [2020-04-23 20:20:45.956] [main] [info] ------------- Starting Sync (******@*****.****.***) ---------------
18396 [2020-04-23 20:20:46.675] [metadata] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   _is_exception_typeof
 ***   _is_exception_typeof
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***
`

**Comment by pythonInRelay** [comment]
Hmm.. it seems that mailspring has deleted my account. I certainly did not delete it myself (I have no idea how to) and that uninstalling the last few versions of Mailspring has not removed all residule files and settings which has given the illusion that my account still works.

Why do I say that my account was deleted? Well it's simple, I didn't delete it. When trying to login it doesn't exist any more apparently. I also cannot seem to recover the account either. It's just gone.

I have the credentials stored in my password vault that stores all of my passwords/usernames etc. however the credentials now magically do not work and the account cannot be found according to Mailspring. Very odd indeed.

Anyway I made a new account and all seems to be finally working. Incredibly shoddy service though. I didn't get any email to my registered address either why you deleted my account.
