### ISSUE TITLE
Starting a reply doesn't immediately capture keystrokes, leading to accidental shortcuts

### ISSUE THREAD

**Issue by axfelix** [Foundry376/Mailspring#672]
Starting a reply to an email thread (e.g. by using the 'r' or 'a' Gmail shortcuts) doesn't seem to *immediately* capture the keyboard -- if I start typing within a few ms I wind up accidentally triggering keyboard shortcuts on other mails in my Inbox.

**Comment by danawoodman** [comment]
Same issue here on OSX with the latest version. This broke after a recently release

**Comment by enoversum** [comment]
I had already reported it recently, and it's still happening :).

**Comment by curtisgibby** [comment]
I've unintentionally archived quite a few unrelated emails by starting to type a reply before the composer window is ready 😢

**Comment by danawoodman** [comment]
This is a hugely annoying issue and causes me to constantly mess up my emails. Please please can this be escalated as it's making me want to ditch Mailspring and just use App Mail (🤮)

**Comment by enoversum** [comment]
Already reported here: https://github.com/Foundry376/Mailspring/issues/560 .

**Comment by danawoodman** [comment]
@bengotow any chance this is being worked on? It is a daily frustration!

**Comment by danawoodman** [comment]
PLEASE PLEASE PLEASE FIX THIS SOON!!!!

**Comment by danawoodman** [comment]
Maybe it is related to https://github.com/ianstormtaylor/slate/issues/1669?

If I know where this is in the code base, I'll take a stab at fixing it

**Comment by danawoodman** [comment]
Starting to worry this project is abandoned just like Nylas...?

**Comment by axfelix** [comment]
Dude, come on, that's not fair at all, he took 12 days off from commits after working like crazy

**Comment by danawoodman** [comment]
@axfelix while I'm sympathetic to whatever the maintainer's situation is, I am also paying for a product that isn't working well and I have been trying for nearly a month to get a reply from the maintainer. I have even offered to help if I could just get some direction as to where to look. I am sure there is a lot of things to address in the product and this may not be a huge priority for the developer(s), but I, as a customer, do feel this is a priority and I am lobbying for it to get addressed in some way. It has been a month and a half with no reply to the original issue so it does feel like this particular issue at least has been ignored/forgotten and I'm trying to change that.

**Comment by enoversum** [comment]
Despite two updates I received for Mailspring today, the issue is still at large, causing me to randomly delete and archive messages 😢 .

**Comment by danawoodman** [comment]
@bengotow it has been two months since this was reported, could you let us know if it is something that is planned to be fixed soon? Thanks!

**Comment by danawoodman** [comment]
Ok, going to try again, any update on this? I will cancel my subscription this week if I don't hear anything back. The lack of response and 420 open issues don't give me much faith I should continue using this product sadly :/

**Comment by jondcallahan** [comment]
Still seeing this issue. Is there any active development on this?

**Comment by curtisgibby** [comment]
Wow, we're coming up on 2 years since this issue was opened. Any update?

**Comment by CodeMouse92** [comment]
Hi all,

Thank you for your patience. Mailspring is not dead, but development *has* been slow for a couple of years. One of the reasons has been the unmaintainable state of the GitHub Issue tracker. (Speaking as the person plowing through those, it's easily 75% duplicates, with many edge case bugs and wishlist feature requests aside.) 2020 also prevented much development. Mailspring is primarily maintained by one person, Ben Gotow, and he does that in addition to a full time job. Mailspring Pro subscriptions mostly cover the costs of APIs and servers for the Pro features.

That explanation understood...

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/starting-a-reply-doesnt-immediately-capture-keystrokes-leading-to-accidental-shortcuts/424

Please consider joining that community and continuing the discussion there! **This bug *is* back on our radar!**

@axfelix: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
