### ISSUE TITLE
Most recent emails will disappear and reappear randomly

### ISSUE THREAD

**Issue by jjohns0003** [Foundry376/Mailspring#96]
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10 Pro

##### What version of Mailspring are you using?
Ver 1.0.2-4eab3f85

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no I am using IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?

n/a

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

**Comment by mfferreira** [comment]
Having the same issue. After selecting emails and deleting them, they come back into my inbox.
I need to delete them again, and sometimes a third time, for the emails to keep deleted.

version: 1.0.2-4eab3f85
os: macOS Sierra 10.12.6 (16G1023)

**Comment by jjohns0003** [comment]
Also, Its weird I will have the most recent email selected so I can read it then I leave it selected but work on my other monitor. Then all of a sudden the 3rd email from the top will be selected and the email client will almost refresh the email list. Also note that at the bottom left it always says Syncing your mailbox...

**Comment by jefftemplon** [comment]
I have what may be a related issue: the inbox says "hooray you're done" and the mails disappear.  I am on a Mac - if I fire up apple mail, i can see the mails sitting there in the inbox.  it's as if in Mailspring, "read" means "done" so read mails no longer are shown?

**Comment by bengotow** [comment]
Hey folks—we haven't seen any reports of this since October so I'm gonna go ahead and close this. It was likely fixed by another patch and we just didn't tie it back to this. Thanks!

**Comment by isfar** [comment]
Same problem. Version `1.7.2`.

**Comment by semihtore** [comment]
This problem continues

**Comment by mfferreira** [comment]
+1

**Comment by Numline1** [comment]
Still having this issue on Version 1.9.1 on macOS. Clicking "Sync New Mail Now" immediately makes the old e-mails reappear.
